import type { Metadata } from 'next';
import { Cormorant_Garamond, DM_Mono, Inter } from 'next/font/google';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { ToastProvider } from '@/components/ui/Toast';
import '@/styles/globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  variable: '--font-serif',
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

const dmMono = DM_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: ['400', '500'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'Visor Index — See Your Advisor Clearly',
    template: '%s | Visor Index',
  },
  description:
    'Search, compare, and connect with SEC-registered investment advisors. Transparent data on fees, AUM, services, and client reviews.',
  metadataBase: new URL('https://visorindex.com'),
  alternates: { canonical: '/' },
  applicationName: 'Visor Index',
  keywords: [
    'financial advisor', 'investment advisor', 'RIA', 'advisor search',
    'advisor comparison', 'SEC advisor', 'fee-only advisor', 'fiduciary',
    'wealth management', 'advisory fees',
  ],
  authors: [{ name: 'Visor Index' }],
  creator: 'Visor Index',
  publisher: 'Visor Index',
  // Icons auto-generated by app/icon.tsx and app/apple-icon.tsx (Next.js file-based convention)
  // Manifest auto-generated by app/manifest.ts
  // OG/Twitter images auto-generated by app/opengraph-image.tsx
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://visorindex.com',
    siteName: 'Visor Index',
    title: 'Visor Index — See Your Advisor Clearly',
    description:
      'Search, compare, and connect with SEC-registered investment advisors. Transparent data on fees, AUM, services, and client reviews.',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Visor Index — See Your Advisor Clearly',
    description:
      'Search, compare, and connect with SEC-registered investment advisors. Transparent data on fees, AUM, services, and client reviews.',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${cormorant.variable} ${dmMono.variable}`}>
      <body className="min-h-screen flex flex-col bg-bg-primary text-text-primary font-sans antialiased">
        <Header />
        <ToastProvider>
          <main className="flex-1">{children}</main>
        </ToastProvider>
        <Footer />
      </body>
    </html>
  );
}
